blank_issues_enabled: true
contact_links:
  - name: Add new ToDo
    about: made by config.yml
    # edit {username} and {repo} for your environment
    url: https://github.com/cube5963/web-manager/issues/new?template=custom.md&projects=cube5963%2Fweb-manager%2F1&labels=ToDo
